services:
#---------------
# NGINX - 
#----------------
  nginx:
    image: owasp/modsecurity-crs:nginx-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ${DATA_PATH}/nginx/ssl:/etc/nginx/ssl:ro #ro c'est pour read-only
    depends_on:
      - frontend
      - backend
    environment:
      - PARANOIA=2                  #level max des regles possibles
      - BLOCKING_PARANOIA=2         #level max des regles used - peut pas etre <PARANOIA
      #Pour savoir si on applique les regles, si on regarde juste ou pas du tout 
      - MODSEC_RULE_ENGINE=On
      #- MODSEC_RULE_ENGINE = DetectionOnly
      #- MODSEC_RULE_ENGINE = Off
      - ANOMALY_INBOUND=5         #score max pour qualifier une requete entrante comme invalide
      - ANOMALY_OUTBOUND=5      #score max pour qualifier une requete sortante comme invalide
    networks:
      - transcendance

#---------------
# BACKEND - Fastify
#---------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    expose:
      - "3001"
    depends_on:
      - db
    networks:
      - transcendance
  
#---------------
# FRONTEND - React/Vite
#---------------
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend
    restart: unless-stopped
    expose:
      - "5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    networks:
      - transcendance

#---------------
# DB - 
#---------------
  db:
    image: public.ecr.aws/docker/library/postgres:16.13-alpine3.23
    expose:
      - "5432"
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - transcendance

#__________________________VOLUMES 
volumes:   
  db-data:
  node_modules:
  
networks:
  transcendance:
    name: transcendance 
    driver: bridge #network driver        #no specific filesystem type
