services:
#---------------
# NGINX -  ATTENTION je sais pas comment configurer nginx, ou mettre son .conf et les certificats ssl
#----------------
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - nginx:/data/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - transcendance

#---------------
# BACKEND - Fastify
#---------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    container_name: backend
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - backend:/data/backend
    networks:
      - transcendance
  
#---------------
# FRONTEND - React/Vite
#---------------
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    container_name: frontend
    restart: unless-stopped
    #environment:
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - frontend:/data/frontend
    networks:
      - transcendance

#---------------
# DB - 
#---------------
  db:
  #peut etre moyen d'appeler directement l'image postgresql
    build:
      context: ./db
      dockerfile: Dockerfile
      target: dev
    container_name: db
    restart: unless-stopped
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PSWD=${DB_PSWD}
    expose:
      - "5432"
    #depends_on:
    #  -  
    volumes:
      - db:/data/database
    networks:
      - transcendance




#__________________________VOLUMES 
volumes: 
  nginx:
    name: nginx
    driver: local
    driver_opts:
      device: ${DATA_PATH}/nginx
      o: bind
      type: none
  db:
    name: db
    driver: local                             #volume driver
    driver_opts:            #volume options 
      device: ${DATA_PATH}/database      #path on the host
      o: bind               #bind mount
      type: none            #no specific filesystem type
  frontend:
    name: frontend
    driver: local                             #volume driver
    driver_opts:            #volume options 
      device: ${DATA_PATH}/frontend      #path on the host
      o: bind               #bind mount
      type: none            #no specific filesystem type
  backend:
    name: backend
    driver: local                             #volume driver
    driver_opts:            #volume options 
      device: ${DATA_PATH}/backend      #path on the host
      o: bind               #bind mount
      type: none    
      
networks:
  transcendance:
    name: transcendance 
    driver: bridge #network driver        #no specific filesystem type
