##Pour rediriger les requests HTTP vers HTTPS

server{  
	listen 80;
	server_name localhost;
	return 301 https://$host$request_uri; 
}

## Gestion des requetes HTTPS

server{
	listen 443 ssl;
	server_name localhost;
	
	ssl_certificate /etc/nginx/ssl/certificat_transcendence.crt;
	ssl_certificate_key /etc/nginx/ssl/certificat_transcendence.key;
	ssl_protocols TLSv1.2 TLSv1.3;

	#pour le backend
	location /api/ {
		proxy_pass http://backend:3001;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	#pour le front
	location / {
		proxy_pass http://frontend:5173;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

	#pour le hot reload de Vite
	#Quand il y a un changement de fichier detecté par Vite, il redirige l'information vers le front via websocket
	location /ws {
		proxy_pass http://frontend:5173;
		#proxy_pass http://backend:3001;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
	}
}
