##Pour rediriger les requests HTTP vers HTTPS

server{  
	listen 80;
	server_name localhost;
	return 301 https://$host$request_uri;
}

## Gestion des requetes HTTPS

server{
	listen 443 ssl;
	server_name localhost;
	
	ssl_certificate ${DATA_PATH}/nginx/ssl/certificat_transcendence.crt;
	ssl_certificate ${DATA_PATH}/nginx/ssl/certificat_transcendence.key;
	ssl_protocols TLSv1.2 TLSv1.3;
}

location /api/ {
	proxy_pass http://backend:3001/ # pour rediriger les requetes qui commencent par /api/
									# on garde le / à la fin car nginx ne passera que la suite(si /api/users => /users)
									# il fait un strip je crois

	#Si on change pas le header, le service pense que c'est nginx le client et pas le vrai user
	#les informations transmises dans le header serait pas les bonnes, on donnerai frontend:5173 au lieu de localhost
	proxy_set_header Host $host     #ici on transmet le nom de domaine original
	proxy_set_header 
		
}


location /ws {

}

#pour rediriger les requetes à destination du frontend (techniquement tous les url qui commence par "/")
location / { 
	proxy_pass http://frontend:5173; #

}